version: "3.8"

services:
  vue-app:
    image: node:16-alpine3.15
    container_name: vue_dev_app
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    command: npm run serve
